version: '3'

services:
  db:
    image: postgres
#    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABSE=library
  web:
    build: .
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db